# -*- coding: utf-8 -*-
"""ggplotGraph.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T5MAC-JtL6lw2MZzzlFoRzU2QQJXkHaQ
"""

#Reference https://python-graph-gallery.com/8-add-confidence-interval-on-barplot/

# libraries
import numpy as np
import matplotlib.pyplot as plt

# width of the bars
barWidth = 0.3

# Choose the height of the blue bars
bars1 = [10.8, 9.5, 4.5, 10.8, 9.5, 4.5, 10.8, 9.5]
 
# Choose the height of the red bars
bars2 = [10.8, 9.5, 4.5, 10.8, 9.5, 4.5, 10.8, 9.5]

# Choose the height of the green bars
bars3 = [10.8, 9.5, 4.5, 10.8, 9.5, 4.5, 10.8, 9.5]
 
# Choose the height of the error bars (bars1)
yer1 = [0.5, 0.4, 0.5, 0.5, 0.4, 0.5, 0.5, 0.4]
 
# Choose the height of the error bars (bars2)
yer2 = [0.5, 0.4, 0.5, 0.5, 0.4, 0.5, 0.5, 0.4]

# Choose the height of the error bars (bars3)
yer3 = [0.5, 0.4, 0.5, 0.5, 0.4, 0.5, 0.5, 0.4]

# The x position of bars
r1 = np.arange(len(bars1))
r2 = [x + barWidth for x in r1]
r3 = [x + barWidth for x in r2]

# Create blue bars
plt.bar(r1, bars1, width = barWidth, color = 'blue', edgecolor = 'black', yerr=yer1, capsize=7, label='ESXi')
 
# Create red bars
plt.bar(r2, bars2, width = barWidth, color = 'red', edgecolor = 'black', yerr=yer2, capsize=7, label='KVM')

# Create green bars
plt.bar(r3, bars3, width = barWidth, color = 'green', edgecolor = 'black', yerr=yer3, capsize=7, label='Native')
 
# general layout
plt.xticks([r + barWidth for r in range(len(bars1))], ['IS', 'EP', 'CG', 'MG', 'FT', 'BT', 'SP', 'LU'])
plt.ylabel('Time in seconds (Lower is better) ')
plt.xlabel('Benchmarks')
plt.legend()

# Show graphic
plt.show()